title: AxiomFactory
description: Radical Minimalism Built from Scratch
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
repository: axiom-factory/usoc
logo: resources/logo.svg
