title: AxiomFactory Blog
description: Building an IoT SoC for a WASM user space
remote_theme: just-the-docs/just-the-docs
plugins:
  - jekyll-remote-theme
gh_repository_url: "https://github.com"
gh_repository_name: "axiom-factory/usoc"
